export interface ApiResponse {
  msg: string;
  id: string;
  error?: string;
}

// Generated by https://quicktype.io

export interface GetDataAppResponse {
  data: DataApp[];
}

export interface DataApp {
  _id: string;
  title: string;
  body: string;
  image: string;
}

export interface GetDataCardsResponse {
  data: DataCard[];
}

export interface DataCard {
  _id: string;
  title: string;
  image: string;
  path: string;
  body: string;
  imageDetails: string;
}

export interface GetDataMaterialsResponse {
  data: DataMaterials[];
}

export interface DataMaterials {
  _id: string;
  title: string;
  items: Item[];
}

export interface Item {
  _id: string;
  title: string;
  image: string;
  href: string;
}

export interface GetDataResponse {
  error?: string
  data: DataApp[] | DataCard[] | DataMaterials[]
}

export interface GetFormsResponse {
  forms: Form[];
}

export interface Form {
  extensionFile: string;
  originalname: string;
  _id: string;
  first_name: string;
  last_name: string;
  msg: string;
  email: string;
  file: string;
  url: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
  icon: string;
  enlace: string;
}

export interface FilesCloudinaryReponse {
  files: FileCloudinary[];
}

export interface FileCloudinary {
  asset_id: string;
  public_id: string;
  format: Format;
  version: number;
  resource_type: ResourceType;
  type: Type;
  created_at: string;
  bytes: number;
  width: number;
  height: number;
  folder: Folder;
  access_mode: AccessMode;
  url: string;
  secure_url: string;
}

export enum AccessMode {
  Public = "public",
}

export enum Folder {
  Cajica = "Cajica",
}

export enum Format {
  Jpg = "jpg",
}

export enum ResourceType {
  Image = "image",
}

export enum Type {
  Upload = "upload",
}
